class ReplitPlatform:
    """Модель платформи Replit відповідно до UML-діаграми прецедентів."""

    def __init__(self, username: str):
        self.username = username
        self.is_authenticated = False
        self.projects = {}

    def authenticate(self, password: str) -> str:
        """Прецедент: Автентифікація."""
        if len(password) < 6:
            raise ValueError("Пароль повинен містити мінімум 6 символів")
        if password == "replit123":
            self.is_authenticated = True
            return "Автентифікація успішна"
        raise PermissionError("Невірний пароль")

    def create_project(self, project_name: str, language: str) -> dict:
        """Прецедент: Створити проєкт (включає Автентифікацію)."""
        if not self.is_authenticated:
            raise RuntimeError("Користувач не автентифікований")
        self.projects[project_name] = {
            "language": language,
            "status": "created",
            "code": ""
        }
        return self.projects[project_name]

    def edit_code(self, project_name: str, new_code: str) -> str:
        """Прецедент: Редагувати код."""
        if project_name not in self.projects:
            raise KeyError("Проєкт не знайдено")
        self.projects[project_name]["code"] = new_code
        return "Код оновлено"

    def ai_generate_code(self, project_name: str, prompt: str) -> str:
        """Прецедент: Згенерувати код через ШІ (розширює Редагувати код)."""
        if not prompt:
            raise ValueError("Запит до ШІ не може бути порожнім")
        generated_code = f"# Generated by AI for prompt: {prompt}\nprint('Hello World')"
        self.edit_code(project_name, generated_code)
        return "Код згенеровано ШІ"

    def deploy_application(self, project_name: str) -> str:
        """Прецедент: Розгорнути додаток (включає Автентифікацію)."""
        if not self.is_authenticated:
            raise RuntimeError("Користувач не автентифікований")
        if project_name not in self.projects:
            raise KeyError("Проєкт не знайдено")
        self.projects[project_name]["status"] = "deployed"
        return "Додаток розгорнуто"

    def run_project(self, project_name: str) -> str:
        """Прецедент: Запустити проєкт."""
        if project_name not in self.projects:
            raise KeyError("Проєкт не знайдено")
        return f"Running project {project_name}..."
